# Generated by Django 6.0.4 on 2026-05-02 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='adverse_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_name',
            field=models.CharField(blank=True, default='Independent', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='co_driver_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='locations_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='num_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='ruleset',
            field=models.CharField(choices=[('70_8', '70 hrs / 8 days'), ('60_7', '60 hrs / 7 days')], default='70_8', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='short_haul',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='split_sleeper_berth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='summary_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_miles',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='truck_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='eld_logs_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trip',
            name='stops_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'created_at'], name='Trips_trip_user_id_c63137_idx'),
        ),
    ]
